name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2-tutor
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: iron
      - run: |
          source /opt/ros/iron/setup.bash
          colcon build